workspace = { members = ["simple_responder"] }
[package]
name = "rust_browser_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.7.0"
druid = "0.7.0"
